### ISSUE TITLE
Unclear Rules to Issue Validator Set Updates

### ISSUE THREAD

**Issue by josef-widder** [althea-net/cosmos-gravity-bridge#205]
Surfaced from [Informal Systems](https://informal.systems/) Gravity Bridge Audit of https://github.com/cosmos/gravity-bridge/commit/df4f1fb4f38d008165760b169637862966d40bb4.

The code of slashing #1 also contains (hides) the [logic that calls SetValsetRequest](https://github.com/cosmos/gravity-bridge/blob/cb2ef3a592ccef0b9eb33ea969b7862f4f7e405b/module/x/peggy/abci.go#L61) if the valset changes more than 1%. The computation of `BridgeValidators` is unclear. It is uncertain how the relayers get the information about the current checkpoint into the Cosmos module.
The 1% rule seems to be a heuristic; its justification is not present. 

### Problem Scenarios

Is there an estimation how often new checkpoints need to be signed? Due to the slashing rule, this might induce a large workload on bonded and unbonding validators. If this happens often, it might be that many Requests are "alive" at the same time, which may lead to races of different `checkpoints` to reach the Solidity contract, which also may induce unnecessary transactions there.

### Recommendation

Clarify the specification and requirements for `SetValsetRequest`.

**Comment by jtremback** [comment]
It sounds like we just need to document this choice in the readme?

**Comment by jkilpatr** [comment]
We should @mankenavenkatesh described the currently implemented ones as.

1. If there are no valset requests, create a new one.
2. If there is atleast one validator who started unbondinging in current block. (we persist last unbonded block height in hooks.go) This will make sure the unbonding validator has to provide an attestation to a new Valset that excludes him before he completely Unbonds.  Otherwise he will be slashed
3. If power change between validators of CurrentValset and latest valset request is > 5%

**Comment by jkilpatr** [comment]
resolved in https://github.com/cosmos/gravity-bridge/pull/288
