### ISSUE TITLE
valset update to peggy contract is missed if relayer doesn't submit before `SignedValsetsWindow`

### ISSUE THREAD

**Issue by mankenavenkatesh** [althea-net/cosmos-gravity-bridge#218]
Valset get's pruned in slashing logic after `SignedValsetsWindow`.

**Problem:**
As valset is pruned after `SignedValsetsWindow`, Relayer misses to submit this valset to Ethereum peggy contract after `SignedValsetsWindow` though it got all the required confirmations.

**Suggestion**
Don't prune valset. Instead do a soft delete.

**Comment by jkilpatr** [comment]
I can agree with this. Especially since by our design estimation it may take several days on prod ethereum between valdiator set updates (simply due to little to no power change on the Cosmos chain) we will need to keep them around at least that long.

It's not a problem on testnets becuase validator set updates are so cheap we simply execute them as soon as possible. I'd lump this into the class of cost optimization bugs we need to do before we hit prod. 

@jackzampolin I know you have strong opinions on state pruning. Do you think we should just provide a longer param for how long we keep validator sets?

**Comment by jkilpatr** [comment]
resolved in #228
