### ISSUE TITLE
Attack Scenario - Withdraw amount on Gravity contract without burning on Cosmos. 

### ISSUE THREAD

**Issue by mankenavenkatesh** [althea-net/cosmos-gravity-bridge#272]
**Context**

- When user sends `SendToEth` tx, we burn the amount and fee, adds OutgoingTransferTx to outgoing pool and appends the txID to unbatched tx id's list.

Reference:
https://github.com/althea-net/cosmos-gravity-bridge/blob/f1bfcfbaadecc950ac04afe73c4d3cda7b442dee/module/x/gravity/keeper/pool.go#L70
 
- When user sends `CancelSendToEth` we remove the entry from the outgoing tx pool and also remove it from unbatched tx id's list and refund back the amount and fee to the user.

Reference:
https://github.com/althea-net/cosmos-gravity-bridge/blob/f1bfcfbaadecc950ac04afe73c4d3cda7b442dee/module/x/gravity/keeper/pool.go#L133

**Problem Statement**
As a malicious user, i will send `SendToEth` tx and wait until an outgoing batch is created which includes my `SendToEth` tx. This eventually gets submitted to Gravity contract and tokens are transferred to my destination address on Ethereum.

Now i will send `CancelSendToEth` tx on cosmos. This will remove the entry from the outgoing tx pool. Then It will try to remove the entry from unbatched tx id's list. `removeFromUnbatchedTXIndex()` throws an error as my tx is added to OutgoingBatch and removed from unbatched tx list. 

As error returned is ignored, it proceeds to next steps and refunds back my amount and fee on cosmos.

https://github.com/althea-net/cosmos-gravity-bridge/blob/f1bfcfbaadecc950ac04afe73c4d3cda7b442dee/module/x/gravity/keeper/pool.go#L133

Yayyyyy......I am able to withdraw amount on Gravity contract and Cancel the withdraw tx on cosmos at same time. :) 

**Solution**
Pretty simple.
If tx id is not available in unbatched tx id's, throw an error and stop `CancelSendToEth` tx.
Once tx is added to Outgoing Batch, user should not be able to cancel the withdraw tx.

**Comment by jkilpatr** [comment]
> Once tx is added to Outgoing Batch, user should not be able to cancel the withdraw tx.

This is the intended behavior. I suppose there's some confusion around the unbatched tx list versus the outgoing tx pool.

By my understanding the outgoing tx pool does not include tx's that are currently in batches, but that may not be the case. I'll investigate.

**Comment by jkilpatr** [comment]
As usual you're correct on this front, let me work on fixing it and adding a test that detects it.

**Comment by jkilpatr** [comment]
Ok, it seems that the original code is correct, or at least correct by accident. 

Here, we try to refund a tx in a batch and fail because it's not found in the pool. 

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/module/x/gravity/keeper/batch_test.go#L498

But I'm not seeing how/where it gets removed from the pool such that we don't find it there in our test. 

Notice here that we are using the second index key and deleting it. 

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/module/x/gravity/keeper/pool.go#L199

Also notice that getPoolTransactions uses that same second index key

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/module/x/gravity/keeper/pool.go#L247

If we where to use getPoolEntry we would retrieve this batched tx and refund it like you describe.

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/module/x/gravity/keeper/pool.go#L230

This is called out in this comment here

https://github.com/althea-net/cosmos-gravity-bridge/blob/main/module/x/gravity/keeper/pool.go#L196

It's 'implicitly not available' becuase it's not longer in the iteration set for GetPoolTransactions.

So this isn't quite an attack vector but it sure is confusing. I'm going to clean this up some with better comments and add a check that the tx is not in the outgoing pool for the refund code, best to double check in case this code is refactored in the future.

**Comment by mankenavenkatesh** [comment]
Yeah...that's true. It's not available in the Unbatched Tx's. 
so we return an error if it is not available here.

https://github.com/althea-net/cosmos-gravity-bridge/blob/f1bfcfbaadecc950ac04afe73c4d3cda7b442dee/module/x/gravity/keeper/pool.go#L217


But this error is ignored and proceeded to refund.
https://github.com/althea-net/cosmos-gravity-bridge/blob/f1bfcfbaadecc950ac04afe73c4d3cda7b442dee/module/x/gravity/keeper/pool.go#L133
